spring.application.name=gateway-service
server.port=8080
spring.cloud.openfeign.circuitbreaker.enabled=false
spring.cloud.openfeign.client.config.cityClient.url=http://localhost:8081/internal/city
spring.cloud.openfeign.client.config.weatherClient.url=http://localhost:8082/internal/weather
spring.cloud.openfeign.client.config.infoClient.url=http://localhost:8083/internal/info
logging.file.path=.
LOGSTASH_HOST=localhost
LOGSTASH_PORT=5044

