spring.application.name=info-service
server.port=8083
spring.cloud.openfeign.circuitbreaker.enabled=true
spring.cloud.openFeign.client.config.wikipediaClient.url=https://pl.wikipedia.org/w/rest.php/v1
spring.cloud.openFeign.client.config.nominatimClient.url=https://nominatim.openstreetmap.org
spring.cloud.openFeign.client.config.frankfurterClient.url=https://api.frankfurter.app
logging.file.path=.
