spring.application.name=city-service
server.port=8081
spring.cloud.openfeign.circuitbreaker.enabled=true
spring.cloud.openfeign.client.config.nominatimClient.url=https://nominatim.openstreetmap.org
logging.file.path=.